apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-1
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-guestbook-1"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/dindo-manondo/argocd-sources.git"
        targetRevision: main
        path: guestbook
      destination:
        server: "{{server}}"
        namespace: guestbook-1
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
