apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diffing-customization-demo
  namespace: argocd
spec:
  destination:
    namespace: diffing-customization-demo
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/dindo-manondo/argocd-sources.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
