apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev-project
  namespace: argocd
spec:
  destination:
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  project: dev-project
  source:
    path: guestbook
    repoURL: "https://github.com/dindo-manondo/argocd-sources.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
