apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/dindo-manondo/argocd-applications-projects.git
  password: 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
  username: dindo-manondo
