apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds # this can be used for all private repos
stringData:
  type: git
  url: https://github.com/dindo-manondo/argocd-applications-projects.git
  password: <TOKEN>
  username: dindo-manondo
